#!/usr/bin/env python

import sys
from subprocess import call


cmd = sys.argv[1]


if(cmd == "start"):
    from coordinator_recv.coordinator_server import ServerLauncher
    launcher = ServerLauncher()
    launcher.start_server()
elif(cmd == "status"):
    call   (["ruby", "status_report/status_report.rb"])
else:
    print "Error: no args"

