#!/bin/bash

# Shell script to start coordinator database logger as an unprivileged
# user. Works around our Upstart's lack of the setuid and setgid
# directives.

# trap '/bin/kill -9 -- 0; exit' 15

while true; do
    su -c 'python -u /usr/local/libexec/coordinator-recv-db.py' sensornet 2>&1 | su -c 'logger -i -t coordinator-recv-db' sensornet
    sleep 1
done
