services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      GATEWAY_DB_URI: 'postgresql://postgres:example@db/postgres'
    command: ["--port", "fake", "--exit-after-n", "3"]
