all:
	make -f makefile.board

test:
	echo "Creating test"


# Include targets for arduino makefile
#
upload:
	make -f makefile.board upload

reset:
	make -f makefile.board reset

do_upload:
	make -f makefile.board do_upload

clean:
	make -f makefile.board clean

